[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
kadena_evm_testnet = "${RPC_URL}"

[etherscan]
kadena_evm_testnet = { key = "YOUR_ETHERSCAN_KEY", url = "${EXPLORER_URL}/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
